/**
 * 小狗照片列表 — file 填 images/ 里的文件名，caption 为悬停时显示的文字
 */
const PHOTOS = [
  { file: "丑小狗01.jpg", caption: "丑小狗 01" },
  { file: "丑小狗02.jpg", caption: "丑小狗 02" },
  { file: "丑小狗03.jpg", caption: "丑小狗 03" },
  { file: "伸懒腰小狗.jpg", caption: "伸懒腰小狗" },
  { file: "可怜小狗01.jpg", caption: "可怜小狗 01" },
  { file: "可怜小狗02.jpg", caption: "可怜小狗 02" },
  { file: "可爱小狗.JPG", caption: "可爱小狗" },
  { file: "和猫哥哥一起的小狗.jpg", caption: "和猫哥哥一起的小狗" },
  { file: "和猫哥哥一起的小狗02.jpg", caption: "和猫哥哥一起的小狗 02" },
  { file: "和猫哥哥一起的小狗03.jpg", caption: "和猫哥哥一起的小狗 03" },
  { file: "回头小狗.jpg", caption: "回头小狗" },
  { file: "大脸小狗.jpg", caption: "大脸小狗" },
  { file: "大脸小狗02.jpg", caption: "大脸小狗 02" },
  { file: "大脸小狗03.jpg", caption: "大脸小狗 03" },
  { file: "大脸小狗04.jpg", caption: "大脸小狗 04" },
  { file: "大脸小狗05.jpg", caption: "大脸小狗 05" },
  { file: "大脸小狗06.jpg", caption: "大脸小狗 06" },
  { file: "委屈小狗.jpg", caption: "委屈小狗" },
  { file: "快乐小狗01.jpg", caption: "快乐小狗 01" },
  { file: "快乐小狗02.jpg", caption: "快乐小狗 02" },
  { file: "懒猪小狗.jpg", caption: "懒猪小狗" },
  { file: "打哈切小狗.jpg", caption: "打哈切小狗" },
  { file: "抱小狗.jpg", caption: "抱小狗" },
  { file: "摔跤小狗.jpg", caption: "摔跤小狗" },
  { file: "看着像笨蛋的小狗.jpg", caption: "看着像笨蛋的小狗" },
  { file: "眯眼小狗.jpg", caption: "眯眼小狗" },
  { file: "眼巴巴小狗.jpg", caption: "眼巴巴小狗" },
  { file: "睡觉小狗.jpg", caption: "睡觉小狗" },
  { file: "睡觉小狗02.jpg", caption: "睡觉小狗 02" },
  { file: "超可爱小狗.jpg", caption: "超可爱小狗" },
];
